# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decree < Formula
  desc "decree — the OpenDecree configuration CLI"
  homepage "https://github.com/opendecree/decree"
  version "0.12.0-alpha.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.3/decree_darwin_amd64.tar.gz"
      sha256 "5f3dd76b8ccea9c0afd5eb09e6fbbe6a31ead702dee70296adea7056fccda61a"

      define_method(:install) do
        bin.install "decree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.3/decree_darwin_arm64.tar.gz"
      sha256 "a67195db568908001df768c62e5e69fa5f6694f3cc4ab24ce5ac9d656601285d"

      define_method(:install) do
        bin.install "decree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.3/decree_linux_amd64.tar.gz"
      sha256 "877bdcb68354f6162d22777b9e593e28c8277a7b493ef1982be575765d5bced5"
      define_method(:install) do
        bin.install "decree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.3/decree_linux_arm64.tar.gz"
      sha256 "010fecd2ebdd9bcdc02cedfa2e70e1379af20353e9eb4a7096fcdcb32c8891bc"
      define_method(:install) do
        bin.install "decree"
      end
    end
  end

  test do
    system "#{bin}/decree", "version"
  end
end
