# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decree < Formula
  desc "decree — the OpenDecree configuration CLI"
  homepage "https://github.com/opendecree/decree"
  version "0.12.0-alpha.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.4/decree_darwin_amd64.tar.gz"
      sha256 "db01ba6d7cc2ad88fd5a3c66e0355166325cc4aafb5320825185fa85410d033a"

      define_method(:install) do
        bin.install "decree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.4/decree_darwin_arm64.tar.gz"
      sha256 "b3431df1533218dbb4f78f1d67fb60153ad56bd3085ad03d7e9c8b6ba90d1630"

      define_method(:install) do
        bin.install "decree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.4/decree_linux_amd64.tar.gz"
      sha256 "4fab6793bbbfbe942f8fb79c2a0354409634df60b5a90a077c0daef11eed694f"
      define_method(:install) do
        bin.install "decree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.4/decree_linux_arm64.tar.gz"
      sha256 "53c1f44c4f917ebdb1dbabe64d9d0605e8437c7d999bf7bfb99e65b1c79a91d9"
      define_method(:install) do
        bin.install "decree"
      end
    end
  end

  test do
    system "#{bin}/decree", "version"
  end
end
