# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decree < Formula
  desc "decree — the OpenDecree configuration CLI"
  homepage "https://github.com/opendecree/decree"
  version "0.12.0-alpha.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.5/decree_darwin_amd64.tar.gz"
      sha256 "9b9a3648a27a12fe07eb6b180f959c364ea4edab1ff6948dd4f8042ef5d0e5c4"

      define_method(:install) do
        bin.install "decree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.5/decree_darwin_arm64.tar.gz"
      sha256 "401d09a2db8f776c3ad0bcd0fddeef970c9b4c8bba98715672141461c3ca4cf2"

      define_method(:install) do
        bin.install "decree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.5/decree_linux_amd64.tar.gz"
      sha256 "5bb7fb4d040dac8eb319c4a0b1f4e445f1bf6fa9299fb6d802243074e9fb494a"
      define_method(:install) do
        bin.install "decree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opendecree/decree/releases/download/v0.12.0-alpha.5/decree_linux_arm64.tar.gz"
      sha256 "f8c1b273494e82441956bc27e5d61382b7e73cb3e87815beb7300c250363bbd7"
      define_method(:install) do
        bin.install "decree"
      end
    end
  end

  test do
    system "#{bin}/decree", "version"
  end
end
