# This formula is auto-generated by goreleaser on each decree release.
# See https://github.com/opendecree/decree/blob/main/.goreleaser.yaml
class Decree < Formula
  desc "decree — the OpenDecree configuration CLI"
  homepage "https://github.com/opendecree/decree"
  license "Apache-2.0"
  version "0.11.0-alpha.1"

  on_macos do
    on_arm do
      url "https://github.com/opendecree/decree/releases/download/v0.11.0-alpha.1/decree_darwin_arm64.tar.gz"
      sha256 "33b6d89d41d71ffb63e3b19d7e5665f9c9f184e978b0e71922f7174b0f7519e2"
    end
    on_intel do
      url "https://github.com/opendecree/decree/releases/download/v0.11.0-alpha.1/decree_darwin_amd64.tar.gz"
      sha256 "f542b793ee003072cad301961c1ee06380f1b2f10bb04f8c7e9c31fc6004e583"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/opendecree/decree/releases/download/v0.11.0-alpha.1/decree_linux_arm64.tar.gz"
      sha256 "4509fb1364bcd1ff0e18972df7e142bf4999d7c9c1b4e897984caeef9bbadbe4"
    end
    on_intel do
      url "https://github.com/opendecree/decree/releases/download/v0.11.0-alpha.1/decree_linux_amd64.tar.gz"
      sha256 "1d4d785b75ad448a1821e2c823d5c9d4bde379482f009a13fb60f248c66933eb"
    end
  end

  def install
    bin.install "decree"
  end

  test do
    system "#{bin}/decree", "version"
  end
end
